apiVersion: v1
kind: Service
metadata:
  namespace: {{ NAMESPACE }}
  name: mysql
  labels:
    service: mysql
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
--
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql
  namespace: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mysql.airb.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mysql
          servicePort: http
