---
  - name: Create content directory
    file:
      path: /var/www/{{ vhost1_Name }}/html
      state: directory
      mode: '0755'
    when: vhost1_Name is defined

  - name: Nginx setup
    apt: pkg=nginx state=latest update_cache=true

  - name: index.html copy for {{ vhost1_Name }}
    template:
      src=../files/index.html.j2
      dest=/var/www/{{ vhost1_Name }}/html/index.html
    when: vhost1_Name is defined
    notify:
      - Restart nginx

  - name: Copy the nginx config for {{ vhost1_Name }}
    template:
      src=../files/{{ vhost1_Name }}.j2
      dest=/etc/nginx/sites-available/{{ vhost1_Name }}
    when: vhost1_Name is defined
    notify:
      - Restart nginx

  - name: Enable new {{ vhost1_Name }}
    file:
      src: /etc/nginx/sites-available/{{ vhost1_Name }}
      dest: /etc/nginx/sites-enabled/{{ vhost1_Name }}
      state: link
    when: vhost1_Name is defined
    notify:
      - Restart nginx

  - name: Copy the nginx config for {{ vhost2_Name }}
    template:
      src=../files/{{ vhost2_Name }}.j2
      dest=/etc/nginx/sites-available/{{ vhost2_Name }}
    when: vhost2_Name is defined
    notify:
      - Restart nginx

  - name: Enable new {{ vhost2_Name }}
    file:
      src: /etc/nginx/sites-available/{{ vhost2_Name }}
      dest: /etc/nginx/sites-enabled/{{ vhost2_Name }}
      state: link
    when: vhost2_Name is defined
    notify:
      - Restart nginx

  - name: Disable nginx default page
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    when: vhost1_Name is defined or vhost2_Name is defined
    notify:
      - Restart nginx

  - name: Enable nginx default page
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
    when: vhost1_Name is undefined and vhost2_Name is undefined
    notify:
      - Restart nginx
